name: "Build IOS & Android"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter  --version

      - name: Flutter analyze
        run: flutter analyze

      - name: Get dependencies
        run: flutter pub get

      - name: Build IOS
        run: flutter build ios --release --no-codesign

      - name: Build Android
        run: flutter build apk --release
