name: "Build"

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter  --version

      - name: Get dependencies
        run: flutter pub get

      - name: Build
        run: flutter build ios --release --no-codesign
